import hashlib
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, Iterable, List, Optional

from jinja2 import Environment, BaseLoader


COMMON_STRINGS = {
    "kernel32.dll",
    "user32.dll",
    "advapi32.dll",
    "ntdll.dll",
    "msvcrt.dll",
    "this program cannot be run in dos mode",
    "getprocaddress",
    "loadlibrarya",
    "loadlibraryw",
    "exitprocess",
}


YARA_TEMPLATE = r'''/*
 Auto-generated by STAS DetectionRuleGenerator.
 Review in a malware lab before production deployment.
*/
import "pe"

rule {{ rule_name }}
{
    meta:
        author = "{{ author }}"
        date = "{{ date }}"
        version = "{{ version }}"
        description = "{{ description }}"
        sample_name = "{{ sample_name }}"
        md5 = "{{ hashes.md5 }}"
        sha1 = "{{ hashes.sha1 }}"
        sha256 = "{{ hashes.sha256 }}"
        imphash = "{{ imphash }}"
        attack = "{{ attack_tags|join(',') }}"

    strings:
{% for item in strings %}
        // {{ item.explanation }}
        $s{{ loop.index }} = {{ item.literal }} {{ item.modifiers }}
{% endfor %}
{% for item in byte_sequences %}
        // {{ item.explanation }}
        $b{{ loop.index }} = { {{ item.hex }} }
{% endfor %}

    condition:
        uint16(0) == 0x5A4D and
        (
{% if strings %}
            // Match unique extracted strings.
            any of them{% if imphash or entropy_conditions or size_condition %} or{% endif %}
{% endif %}
{% if byte_sequences and not strings %}
            // Match malware-specific byte sequences.
            any of ($b*){% if imphash or entropy_conditions or size_condition %} or{% endif %}
{% endif %}
{% if imphash %}
            // Match import hash observed in the analyzed sample.
            pe.imphash() == "{{ imphash }}"{% if entropy_conditions or size_condition %} or{% endif %}
{% endif %}
{% if entropy_conditions %}
            // Match suspicious section entropy characteristics.
            (
{% for cond in entropy_conditions %}
                {{ cond }}{% if not loop.last %} or{% endif %}
{% endfor %}
            ){% if size_condition %} or{% endif %}
{% endif %}
{% if size_condition %}
            // Match observed file size range with tolerance.
            {{ size_condition }}
{% endif %}
        )
}
'''


SIGMA_TEMPLATE = '''title: {{ title }}
id: {{ rule_id }}
status: experimental
description: {{ description }}
author: {{ author }}
date: {{ date }}
references:
  - https://attack.mitre.org/
tags:
{% for tag in tags %}
  - {{ tag }}
{% endfor %}
logsource:
  product: windows
  service: sysmon
detection:
{% if process_selection %}
  selection_process:
{% for key, values in process_selection.items() %}
    {{ key }}:
{% for value in values %}
      - '{{ value }}'
{% endfor %}
{% endfor %}
{% endif %}
{% if registry_selection %}
  selection_registry:
    EventID:
      - 12
      - 13
      - 14
    TargetObject|contains:
{% for value in registry_selection %}
      - '{{ value }}'
{% endfor %}
{% endif %}
{% if network_selection %}
  selection_network:
    EventID: 3
{% if network_selection.ips %}
    DestinationIp:
{% for value in network_selection.ips %}
      - '{{ value }}'
{% endfor %}
{% endif %}
{% if network_selection.domains %}
    DestinationHostname|contains:
{% for value in network_selection.domains %}
      - '{{ value }}'
{% endfor %}
{% endif %}
{% endif %}
{% if file_selection %}
  selection_file:
    EventID:
      - 11
      - 23
      - 26
    TargetFilename|contains:
{% for value in file_selection %}
      - '{{ value }}'
{% endfor %}
{% endif %}
  condition: {{ condition }}
falsepositives:
  - Legitimate administration or software update behavior matching these paths or network indicators.
  - Security testing tools in approved lab environments.
level: {{ level }}
'''


@dataclass
class YaraString:
    value: str
    literal: str
    modifiers: str
    explanation: str


class DetectionRuleGenerator:
    def __init__(
        self,
        author: str = "STAS",
        version: str = "1.0",
        max_yara_strings: int = 20,
    ):
        self.author = author
        self.version = version
        self.max_yara_strings = max_yara_strings
        self.env = Environment(loader=BaseLoader(), autoescape=False, trim_blocks=False, lstrip_blocks=False)

    def generate_yara(self, analysis_results: Dict[str, Any]) -> str:
        sample = self._sample(analysis_results)
        hashes = self._hashes(analysis_results)
        strings = self._select_yara_strings(analysis_results)
        byte_sequences = self._byte_sequences(analysis_results)
        entropy_conditions = self._entropy_conditions(analysis_results)
        size_condition = self._size_condition(sample.get("size"))
        imphash = str(sample.get("imphash") or analysis_results.get("imphash") or "").lower()
        attack_tags = self._attack_tags(analysis_results)
        family = self._family_name(analysis_results)

        rendered = self.env.from_string(YARA_TEMPLATE).render(
            rule_name=self._yara_rule_name(family, sample.get("name")),
            author=self._escape_meta(self.author),
            date=self._date(),
            version=self._escape_meta(self.version),
            description=self._escape_meta(f"Detects {family or 'malware sample'} using strings, imphash, entropy, and size traits"),
            sample_name=self._escape_meta(str(sample.get("name") or "unknown")),
            hashes={key: self._escape_meta(value) for key, value in hashes.items()},
            imphash=self._escape_meta(imphash),
            attack_tags=attack_tags,
            strings=[item.__dict__ for item in strings],
            byte_sequences=byte_sequences,
            entropy_conditions=entropy_conditions,
            size_condition=size_condition,
        )
        return self._cleanup_blank_lines(rendered)

    def generate_sigma(self, analysis_results: Dict[str, Any]) -> str:
        sample = self._sample(analysis_results)
        family = self._family_name(analysis_results)
        events = self._events(analysis_results)
        iocs = self._iocs(analysis_results)
        attack_tags = self._attack_tags(analysis_results)

        process_selection = self._process_selection(events)
        registry_selection = self._registry_selection(analysis_results, events, iocs)
        network_selection = {
            "ips": self._dedupe(iocs.get("ips", []))[:20],
            "domains": self._dedupe(iocs.get("domains", []))[:20],
        }
        file_selection = self._file_selection(analysis_results, events, iocs)
        if not process_selection and not registry_selection and not network_selection["ips"] and not network_selection["domains"] and not file_selection:
            sample_name = sample.get("name")
            if sample_name:
                process_selection = {"Image|endswith": [str(sample_name)]}
        condition_parts = []
        if process_selection:
            condition_parts.append("selection_process")
        if registry_selection:
            condition_parts.append("selection_registry")
        if network_selection["ips"] or network_selection["domains"]:
            condition_parts.append("selection_network")
        if file_selection:
            condition_parts.append("selection_file")
        condition = " or ".join(condition_parts) if condition_parts else "selection_process"

        rendered = self.env.from_string(SIGMA_TEMPLATE).render(
            title=f"STAS Malware Behavior - {family or sample.get('name') or 'Unknown Sample'}",
            rule_id=self._stable_uuid(f"sigma:{sample.get('sha256') or sample.get('name') or family}"),
            description=f"Detects Sysmon telemetry associated with {family or 'the analyzed malware sample'}.",
            author=self.author,
            date=self._date(),
            tags=attack_tags or ["attack.execution"],
            process_selection=process_selection,
            registry_selection=registry_selection,
            network_selection=network_selection,
            file_selection=file_selection,
            condition=condition,
            level=self._sigma_level(analysis_results),
        )
        return self._cleanup_blank_lines(rendered)

    def generate_ioc_report(self, analysis_results: Dict[str, Any]) -> str:
        sample = self._sample(analysis_results)
        hashes = self._hashes(analysis_results)
        iocs = self._iocs(analysis_results)
        attack_tags = self._attack_tags(analysis_results)

        rows = []
        for key, label in [("ips", "IP"), ("domains", "Domain"), ("urls", "URL"), ("files", "File"), ("registry", "Registry")]:
            for value in self._dedupe(iocs.get(key, [])):
                rows.append((label, self.defang(str(value))))

        lines = [
            "# STAS IOC Summary",
            "",
            f"- Sample: `{sample.get('name') or 'unknown'}`",
            f"- Generated: `{self._date()}`",
            f"- ATT&CK: `{', '.join(attack_tags) if attack_tags else 'N/A'}`",
            "",
            "## Hashes",
            "",
            "| Type | Value |",
            "|---|---|",
        ]
        for key in ["md5", "sha1", "sha256", "imphash"]:
            value = hashes.get(key) or sample.get(key) or analysis_results.get(key)
            if value:
                lines.append(f"| {key.upper()} | `{value}` |")

        lines.extend(["", "## Defanged IOCs", "", "| Type | Value |", "|---|---|"])
        if rows:
            lines.extend(f"| {ioc_type} | `{value}` |" for ioc_type, value in rows)
        else:
            lines.append("| None | `No IOCs provided` |")

        lines.extend(
            [
                "",
                "## Copy/Paste IOC Block",
                "",
                "```text",
            ]
        )
        for _, value in rows:
            lines.append(value)
        lines.extend(
            [
                "```",
                "",
                "## Detection Recommendations",
                "",
                "- YARA: prioritize unique strings, imphash, section entropy, and size constraints from this sample.",
                "- Sigma: monitor Sysmon process creation, registry modifications, network connections, and file writes tied to the listed IOCs.",
                "- Validate all generated rules in a lab before production deployment.",
            ]
        )
        return "\n".join(lines)

    def _select_yara_strings(self, analysis: Dict[str, Any]) -> List[YaraString]:
        candidates = []
        for key in ["strings", "unique_strings", "extracted_strings"]:
            candidates.extend(self._string_list(analysis.get(key)))
        candidates.extend(self._string_list(analysis.get("static", {}).get("strings")))
        candidates.extend(self._string_list(analysis.get("static", {}).get("unique_strings")))
        candidates.extend(self._flatten_iocs_as_strings(analysis))

        selected = []
        seen = set()
        for value in candidates:
            cleaned = value.strip("\x00\r\n\t ")
            lower = cleaned.lower()
            if lower in seen or not self._is_useful_yara_string(cleaned):
                continue
            seen.add(lower)
            selected.append(
                YaraString(
                    value=cleaned,
                    literal=self._yara_string_literal(cleaned),
                    modifiers="ascii wide",
                    explanation=self._string_explanation(cleaned),
                )
            )
            if len(selected) >= self.max_yara_strings:
                break
        return selected

    def _byte_sequences(self, analysis: Dict[str, Any]) -> List[Dict[str, str]]:
        values = analysis.get("byte_sequences") or analysis.get("static", {}).get("byte_sequences") or []
        result = []
        for item in values[:10]:
            if isinstance(item, dict):
                raw = str(item.get("hex") or item.get("bytes") or "")
                explanation = str(item.get("explanation") or "Specific byte sequence observed in sample")
            else:
                raw = str(item)
                explanation = "Specific byte sequence observed in sample"
            hex_value = self._normalize_hex_sequence(raw)
            if hex_value:
                result.append({"hex": hex_value, "explanation": explanation})
        return result

    def _entropy_conditions(self, analysis: Dict[str, Any]) -> List[str]:
        entropy = analysis.get("static", {}).get("entropy_scores") or analysis.get("entropy_scores") or []
        conditions = []
        if isinstance(entropy, list):
            high_sections = [item for item in entropy if self._entropy_value(item) and self._entropy_value(item) > 7.2]
            if high_sections:
                conditions.append("for any i in (0..pe.number_of_sections - 1): (pe.sections[i].entropy > 7.2)")
            very_high = [item for item in entropy if self._entropy_value(item) and self._entropy_value(item) > 7.5]
            if very_high:
                conditions.append("for any i in (0..pe.number_of_sections - 1): (pe.sections[i].entropy > 7.5)")
        return conditions

    def _size_condition(self, size: Any) -> str:
        try:
            value = int(size)
        except (TypeError, ValueError):
            return ""
        lower = max(0, int(value * 0.85))
        upper = int(value * 1.15) + 1
        return f"filesize >= {lower} and filesize <= {upper}"

    def _process_selection(self, events: List[Dict[str, Any]]) -> Dict[str, List[str]]:
        images = []
        parents = []
        command_lines = []
        for event in events:
            event_type = str(event.get("event_type") or event.get("type") or "").lower()
            if "process" not in event_type and event.get("Image") is None:
                continue
            for key in ["process_name", "Image", "image"]:
                if event.get(key):
                    images.append(str(event[key]))
            for key in ["parent_process", "ParentImage", "parent_image"]:
                if event.get(key):
                    parents.append(str(event[key]))
            for key in ["command_line", "CommandLine", "cmdline"]:
                if event.get(key):
                    command_lines.append(str(event[key]))
        result = {}
        if images:
            result["Image|endswith"] = self._dedupe(images)[:20]
        if parents:
            result["ParentImage|endswith"] = self._dedupe(parents)[:20]
        if command_lines:
            result["CommandLine|contains"] = self._dedupe(command_lines)[:20]
        return result

    def _registry_selection(self, analysis: Dict[str, Any], events: List[Dict[str, Any]], iocs: Dict[str, List[str]]) -> List[str]:
        values = list(iocs.get("registry", []))
        values.extend(self._string_list(analysis.get("dynamic", {}).get("persistence_mechanisms")))
        for event in events:
            event_type = str(event.get("event_type") or event.get("type") or "").lower()
            if "reg" in event_type:
                values.extend(self._event_values(event, ["target_object", "TargetObject", "registry_key", "key", "description"]))
        return self._dedupe([value for value in values if "\\" in str(value)])[:30]

    def _file_selection(self, analysis: Dict[str, Any], events: List[Dict[str, Any]], iocs: Dict[str, List[str]]) -> List[str]:
        values = list(iocs.get("files", []))
        for event in events:
            event_type = str(event.get("event_type") or event.get("type") or "").lower()
            if "file" in event_type:
                values.extend(self._event_values(event, ["target_filename", "TargetFilename", "path", "file_path", "description"]))
        suffixes = [".exe", ".dll", ".ps1", ".vbs", ".bat", ".tmp", ".dat"]
        values.extend(value for value in suffixes if any(value in str(item).lower() for item in values))
        return self._dedupe(values)[:30]

    def _iocs(self, analysis: Dict[str, Any]) -> Dict[str, List[str]]:
        raw = analysis.get("iocs") or analysis.get("ioc_summary") or {}
        result = {"ips": [], "domains": [], "urls": [], "files": [], "registry": []}
        if isinstance(raw, dict):
            for key in result:
                result[key].extend(self._string_list(raw.get(key)))
            result["ips"].extend(self._string_list(raw.get("ip_addresses")))
            result["urls"].extend(self._string_list(raw.get("url")))
            result["registry"].extend(self._string_list(raw.get("registry_keys")))
        elif isinstance(raw, list):
            for item in raw:
                if not isinstance(item, dict):
                    continue
                value = str(item.get("value") or "")
                ioc_type = str(item.get("type") or "").upper()
                if not value:
                    continue
                if "IP" in ioc_type:
                    result["ips"].append(value)
                elif "DOMAIN" in ioc_type:
                    result["domains"].append(value)
                elif "URL" in ioc_type:
                    result["urls"].append(value)
                elif "REG" in ioc_type:
                    result["registry"].append(value)
                else:
                    result["files"].append(value)
        return {key: self._dedupe(values) for key, values in result.items()}

    def _events(self, analysis: Dict[str, Any]) -> List[Dict[str, Any]]:
        events = analysis.get("dynamic", {}).get("events") or analysis.get("behavioral_events") or []
        return [event for event in events if isinstance(event, dict)]

    def _sample(self, analysis: Dict[str, Any]) -> Dict[str, Any]:
        return analysis.get("sample") or analysis.get("file") or {}

    def _hashes(self, analysis: Dict[str, Any]) -> Dict[str, str]:
        sample = self._sample(analysis)
        hashes = analysis.get("hashes") if isinstance(analysis.get("hashes"), dict) else {}
        return {
            "md5": str(sample.get("md5") or hashes.get("md5") or ""),
            "sha1": str(sample.get("sha1") or hashes.get("sha1") or ""),
            "sha256": str(sample.get("sha256") or hashes.get("sha256") or ""),
            "imphash": str(sample.get("imphash") or analysis.get("imphash") or hashes.get("imphash") or ""),
        }

    def _attack_tags(self, analysis: Dict[str, Any]) -> List[str]:
        techniques = analysis.get("attack_techniques") or []
        tags = []
        for item in techniques:
            technique_id = item.get("id") if isinstance(item, dict) else str(item)
            if technique_id:
                tags.append(f"attack.{str(technique_id).lower()}")
        return self._dedupe(tags)

    def _family_name(self, analysis: Dict[str, Any]) -> str:
        ml = analysis.get("ml_prediction") or {}
        return str(ml.get("likely_family") or ml.get("family") or analysis.get("family") or "").strip()

    def _sigma_level(self, analysis: Dict[str, Any]) -> str:
        overall = analysis.get("risk_scores", {}).get("overall", 0)
        try:
            score = int(overall)
        except (TypeError, ValueError):
            score = 0
        if score >= 85:
            return "critical"
        if score >= 65:
            return "high"
        if score >= 35:
            return "medium"
        return "low"

    def _flatten_iocs_as_strings(self, analysis: Dict[str, Any]) -> List[str]:
        iocs = self._iocs(analysis)
        values = []
        for key in ["domains", "urls", "files", "registry"]:
            values.extend(iocs.get(key, []))
        return values

    def _is_useful_yara_string(self, value: str) -> bool:
        lower = value.lower()
        if len(value) < 6 or len(value) > 180:
            return False
        if lower in COMMON_STRINGS:
            return False
        if lower.endswith((".dll", ".pdb")) and "\\" not in value:
            return False
        if re.fullmatch(r"[A-Za-z0-9_.$-]+", value) and len(set(value.lower())) < 5:
            return False
        printable_ratio = sum(1 for ch in value if ch.isprintable()) / max(1, len(value))
        return printable_ratio > 0.9

    def _string_explanation(self, value: str) -> str:
        if value.startswith(("http://", "https://")):
            return "Network indicator URL extracted from sample"
        if "\\" in value and ("HK" in value.upper() or "HKEY" in value.upper()):
            return "Registry path associated with sample behavior"
        if "\\" in value or "/" in value:
            return "File path or filesystem artifact extracted from sample"
        if "." in value:
            return "Domain or dotted indicator extracted from sample"
        return "Unique string extracted from sample"

    def _yara_string_literal(self, value: str) -> str:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'

    def _normalize_hex_sequence(self, value: str) -> str:
        cleaned = re.sub(r"[^0-9A-Fa-f?]", "", value)
        if len(cleaned) < 8:
            return ""
        if len(cleaned) % 2:
            cleaned = cleaned[:-1]
        pairs = [cleaned[index : index + 2] for index in range(0, len(cleaned), 2)]
        return " ".join(pair.upper() for pair in pairs[:128])

    def _entropy_value(self, item: Any) -> Optional[float]:
        if isinstance(item, dict):
            item = item.get("entropy")
        try:
            return float(item)
        except (TypeError, ValueError):
            return None

    def _string_list(self, value: Any) -> List[str]:
        if value is None:
            return []
        if isinstance(value, str):
            return [value]
        if isinstance(value, dict):
            return [str(item) for item in value.values() if item]
        if isinstance(value, Iterable):
            result = []
            for item in value:
                if isinstance(item, dict):
                    result.append(str(item.get("value") or item.get("name") or item.get("path") or item))
                elif item:
                    result.append(str(item))
            return result
        return [str(value)]

    def _event_values(self, event: Dict[str, Any], keys: List[str]) -> List[str]:
        values = []
        for key in keys:
            if event.get(key):
                values.append(str(event[key]))
        raw = event.get("raw_data")
        if isinstance(raw, dict):
            for key in keys:
                if raw.get(key):
                    values.append(str(raw[key]))
        return values

    def _dedupe(self, values: Iterable[Any]) -> List[str]:
        result = []
        seen = set()
        for value in values:
            text = str(value).strip()
            if not text:
                continue
            key = text.lower()
            if key not in seen:
                seen.add(key)
                result.append(text)
        return result

    def _yara_rule_name(self, family: str, sample_name: Any) -> str:
        base = family or str(sample_name or "sample")
        sanitized = re.sub(r"[^A-Za-z0-9_]", "_", base)
        sanitized = re.sub(r"_+", "_", sanitized).strip("_")
        if not sanitized or not sanitized[0].isalpha():
            sanitized = "Malware_" + sanitized
        return f"STAS_{sanitized[:48]}"

    def _stable_uuid(self, value: str) -> str:
        digest = hashlib.sha256(value.encode("utf-8")).hexdigest()
        return f"{digest[0:8]}-{digest[8:12]}-4{digest[13:16]}-8{digest[17:20]}-{digest[20:32]}"

    def _escape_meta(self, value: Any) -> str:
        return str(value or "").replace("\\", "\\\\").replace('"', '\\"')

    def _date(self) -> str:
        return datetime.now(timezone.utc).date().isoformat()

    def _cleanup_blank_lines(self, text: str) -> str:
        lines = [line.rstrip() for line in text.splitlines()]
        return "\n".join(lines).strip() + "\n"

    def defang(self, value: str) -> str:
        text = value.replace("http://", "hxxp://").replace("https://", "hxxps://")
        return text.replace(".", "[.]")


if __name__ == "__main__":
    sample = {
        "sample": {
            "name": "sample.exe",
            "sha256": "a" * 64,
            "md5": "b" * 32,
            "size": 245760,
            "imphash": "0123456789abcdef0123456789abcdef",
        },
        "static": {
            "strings": ["C:\\Users\\Public\\svchost.exe", "bad.example.com", "kernel32.dll"],
            "entropy_scores": [{"name": ".text", "entropy": 7.4}],
            "byte_sequences": ["4D 5A 90 00 03 00 00 00"],
        },
        "dynamic": {
            "events": [
                {"event_type": "ProcessCreate", "process_name": "svchost.exe", "parent_process": "cmd.exe"},
                {"event_type": "RegistryModify", "target_object": "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\Updater"},
            ],
            "persistence_mechanisms": ["HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\Updater"],
        },
        "attack_techniques": [{"id": "T1055"}, {"id": "T1547.001"}],
        "iocs": {"domains": ["bad.example.com"], "files": ["C:\\Users\\Public\\svchost.exe"], "registry": []},
        "ml_prediction": {"likely_family": "ExampleLoader"},
        "risk_scores": {"overall": 80},
    }
    generator = DetectionRuleGenerator()
    print(generator.generate_yara(sample))
    print(generator.generate_sigma(sample))
    print(generator.generate_ioc_report(sample))
